//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_BangCong
    {
        public int ID_BC { get; set; }
        public int Nam { get; set; }
        public int Thang { get; set; }
        public int Ngay { get; set; }
        public int GioVao { get; set; }
        public int PhutVao { get; set; }
        public Nullable<int> GiayVao { get; set; }
        public int GioRa { get; set; }
        public int PhutRa { get; set; }
        public Nullable<int> GiayRa { get; set; }
        public int ID_NV { get; set; }
        public int ID_LoaiCong { get; set; }
    
        public virtual tb_NhanVien tb_NhanVien { get; set; }
        public virtual tb_LoaiCong tb_LoaiCong { get; set; }
    }
}
