//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_BangCong_NV_CT
    {
        public int ID { get; set; }
        public string MaKyCong { get; set; }
        public string TenNV { get; set; }
        public string ID_NV { get; set; }
        public System.DateTime Ngay { get; set; }
        public string Thu { get; set; }
        public string GioVao { get; set; }
        public string GioRa { get; set; }
        public Nullable<double> NgayThuong { get; set; }
        public Nullable<double> NgayPhep { get; set; }
        public Nullable<double> NgayKhongPhep { get; set; }
        public Nullable<double> NgayLe { get; set; }
        public Nullable<double> NgayChuNhat { get; set; }
        public string KyHieu { get; set; }
        public string GhiChu { get; set; }
        public string Create_By { get; set; }
        public Nullable<System.DateTime> Create_Time { get; set; }
        public string Update_By { get; set; }
        public Nullable<System.DateTime> Update_Time { get; set; }
    
        public virtual tb_NhanVien tb_NhanVien { get; set; }
    }
}
