//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DieuChuyen
    {
        public string SoQD { get; set; }
        public System.DateTime NgayApDung { get; set; }
        public System.DateTime NgayKi { get; set; }
        public string ID_NV { get; set; }
        public string ID_NV_Duyet { get; set; }
        public string ID_PB { get; set; }
        public string ID_BP { get; set; }
        public string ID_PBNew { get; set; }
        public string ID_BPNew { get; set; }
        public string LiDo { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> Create_By { get; set; }
        public Nullable<System.DateTime> Create_Time { get; set; }
        public Nullable<int> Update_By { get; set; }
        public Nullable<System.DateTime> Update_Time { get; set; }
        public Nullable<int> Delete_By { get; set; }
        public Nullable<System.DateTime> Delete_Time { get; set; }
    
        public virtual tb_NhanVien tb_NhanVien { get; set; }
    }
}
