//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NhanVien_PhuCap
    {
        public int ID { get; set; }
        public int ID_NV { get; set; }
        public int ID_PC { get; set; }
        public System.DateTime Ngay { get; set; }
        public string NoiDung { get; set; }
        public double SoTien { get; set; }
    
        public virtual tb_NhanVien tb_NhanVien { get; set; }
        public virtual tb_PhuCap tb_PhuCap { get; set; }
    }
}
