//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_SYS_User
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public string Role { get; set; }
        public string ID_NV { get; set; }
        public Nullable<System.DateTime> Last_PWD_Change { get; set; }
        public Nullable<bool> Disable { get; set; }
    
        public virtual tb_NhanVien tb_NhanVien { get; set; }
    }
}
