//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_TangCa
    {
        public string ID_TC { get; set; }
        public System.DateTime NgayTC { get; set; }
        public double SoGio { get; set; }
        public string ID_NV { get; set; }
        public double HeSo { get; set; }
        public decimal SoTien { get; set; }
        public string GhiChu { get; set; }
        public string Create_By { get; set; }
        public Nullable<System.DateTime> Create_Time { get; set; }
        public string Update_By { get; set; }
        public Nullable<System.DateTime> Update_Time { get; set; }
        public string Delete_By { get; set; }
        public Nullable<System.DateTime> Delete_Time { get; set; }
    
        public virtual tb_NhanVien tb_NhanVien { get; set; }
    }
}
