//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ThangTien
    {
        public string SoQD { get; set; }
        public string SoHD { get; set; }
        public Nullable<int> ID_NV { get; set; }
        public Nullable<double> LuongThoaThuan_OLD { get; set; }
        public Nullable<double> LuongThoaThuan_NEW { get; set; }
        public string GhiChu { get; set; }
        public string LyDo { get; set; }
        public Nullable<System.DateTime> NgayApDung { get; set; }
        public Nullable<System.DateTime> NgayKy { get; set; }
        public Nullable<int> Create_By { get; set; }
        public Nullable<System.DateTime> Create_Time { get; set; }
        public Nullable<int> Update_By { get; set; }
        public Nullable<System.DateTime> Update_Time { get; set; }
        public Nullable<int> Delete_By { get; set; }
        public Nullable<System.DateTime> Delete_Time { get; set; }
        public Nullable<int> ID_CV_Old { get; set; }
        public Nullable<int> ID_CV_New { get; set; }
    
        public virtual tb_HopDong tb_HopDong { get; set; }
        public virtual tb_NhanVien tb_NhanVien { get; set; }
    }
}
