//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_UngLuong
    {
        public int ID_UL { get; set; }
        public int Nam { get; set; }
        public int Thang { get; set; }
        public int Ngay { get; set; }
        public double SoTien { get; set; }
        public bool TrangThai { get; set; }
        public int ID_NV { get; set; }
    
        public virtual tb_NhanVien tb_NhanVien { get; set; }
    }
}
